### ISSUE TITLE
@JsonRootName Not Working for  Collection Type 

### ISSUE THREAD

**Issue by haribachala** [FasterXML/jackson-module-jaxb-annotations#44] opened 2015-07-06 05:22 UTC
The following is the test case.

------------------
POJO Classs
-----------------

```java
@JsonRootName("Employee")
public class Employee implements Serializable {

     private String empName;
     private String empNo;
     public String getEmpName() {
          return empName;
     }
  public void setEmpName(String empName) {
          this.empName = empName;
     }
     public String getEmpNo() {
          return empNo;
     }
     public void setEmpNo(String empNo) {
          this.empNo = empNo;
     }
}
```

TEST CASE

```java
public class EmployeeTest {
    @Test
    public void testEMPJsonData() throws  Exception{

        Employee emp =new Employee();
        emp.setEmpName("john");
        emp.setEmpNo("1234");
        emp.setPermentAddress("india");
        List<Employee> empList = new ArrayList<Employee>();
        empList.add(emp);
        /********** - JACKSON *******************/
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(MapperFeature.USE_WRAPPER_NAME_AS_PROPERTY_NAME, true);
        mapper.configure(SerializationFeature.WRAP_ROOT_VALUE, true);
        mapper.setAnnotationIntrospector(new AnnotationIntrospectorPair(new  JacksonAnnotationIntrospector(), new JaxbAnnotationIntrospector(TypeFactory.defaultInstance())));
        mapper.writeValue(System.out, empList); 
 
    }
}
```

----------------
ouput

```json
{"ArrayList":[{"empName":"john","empNo":"1234"}]}
```

Expected : 

    {"Employee":[{"empName":"john","empNo":"1234"}]}

why it behaving like this for collections?

**Comment by haribachala** [comment] 2015-07-08 12:15
moved to jackson-annotations project

**Comment by cowtowncoder** [comment] 2015-07-08 16:09
No, while annotations may be defined in jackson-annotations, none of handling is.
So this belongs either here, or under `jackson-databind`.

**Comment by cowtowncoder** [comment] 2015-07-08 16:13
As to the issue: collections are first class types, and not just a sequence of elements. As such, wrapper name is taken from container class itself, same as with POJOs. That is why `ArrayList` is the expected default name.

But what you probably want to do is either:

1. Create sub-class of your own, like `public class MyList<T> extends ArrayList<T> { }` which has `@JsonRootName` annotation
2. Use `ObjectWriter`; something like:

    ObjectWriter w = mapper.writer().withRootName("Employee");
    w.writeValue(output, listValue);

Note that in second case, you also need to use `ObjectReader` to read it, with similar specification of root name to expect.

**Comment by haribachala** [comment] 2015-07-09 04:36
Thanks

May be option 1 will work for me.
"
we are creating only one ObjectMapper instance for whole project so hard coding "withRootName("Employee");"  is difficult.

**Comment by cowtowncoder** [comment] 2015-07-09 17:28
I think you misunderstood me wrt `ObjectWriter`: you do not (and can not) specify root name for `ObjectMapper`: you specify that for `ObjectWriter`; instances of which may be shared, or re-created on per-call basis. So if you handle serialization directly, code example from above works using a single shared `mapper`, which is not modified. Just `ObjectWriter`, created locally, is modified.

Regardless, behavior of naming works as intended, so I will close this issue.

**Closed** 2015-07-09 19:31 UTC

**Comment by acpoorni81** [comment] 2016-04-28 19:14
@haribachala  ..I am facing an issue where i dont get the JSON Root name in the reponse. How did u resolve this ?
